Components modification
AMikhnyuk/component_modification pull request #1
Opened 2021-09-30 18:06 UTC by AMikhnyuk

2021-09-30 19:47 UTC, HelgaListopad requested changes

2021-09-30 19:47 UTC, HelgaListopad commented on js/main.js
> +          if (config.saveAction) $$("save").attachEvent("onItemClick", config.saveAction);
Не хватает дефолтных обработчиков клика:

> - set default actions for Cancel and Save buttons
>   - default actions should be called only if these actions are not reset in the configuration

2021-09-30 19:47 UTC, HelgaListopad commented on js/main.js
> +        const els = config.elements;
`elements` лучше задать здесь по умолчанию как пустой массив и убрать из конфигурации webix.ui

2021-09-30 19:47 UTC, HelgaListopad commented on js/main.js
> +          if (field === "one") els.push({ view: "text", label: "Fname" });
По идее этого задания, форма должна создавать инпуты для _любых_ полей, чьи имена прописаны в `fields`.

Здесь понадобится не проверка на конкретные три имени, а универсальная логика, которая бы добавляла текстовый инпут с `name` (вспомни, что без этого не достать значение через `form.getValues()`) и `label`.

2021-09-30 22:11 UTC, HelgaListopad commented on js/main.js
> +          const save = $$("save");
Глобальные ID здесь не подойдут - ты создаёшь кастомный компонент, который может переиспользоваться
Попробуй `queryView`

2021-10-01 06:43 UTC, tsemashko commented on js/main.js
> +            { view: "button", value: "Save", css: "webix_primary", width: 150, id: "save" }
глобальные id лучше убрать из protoUI

2021-10-01 07:58 UTC, HelgaListopad commented on js/main.js
> +          if (field === "one") els.push({ view: "text", label: "Fname" });
Label нужен  - надо всё-таки дать пользователю понимание того, какое поле он заполняет.
Он может просто совпадать с переданной строкой, но начинаться с заглавной буквы

2021-10-01 08:11 UTC, tsemashko approved these changes

2021-10-04 07:59 UTC, HelgaListopad approved these changes

2021-10-04 09:25 UTC, merged